services:
  - type: web
    name: signalor-geo-app
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SIGNALOR_HMAC_SECRET
        sync: false
      - key: SIGNALOR_SHOPIFY_APP_HMAC_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        value: https://app.signalor.ai
      - key: SCOPES
        value: read_products,write_products,read_content,write_content,read_metaobjects,write_metaobjects,read_themes,write_themes,read_customers,read_orders
      - key: DATABASE_URL
        sync: false
