-- Add missing Shopify session fields
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "accountOwner" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "locale" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "collaborator" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT false;
